version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: teste-tecnico-db
    environment:
      SA_PASSWORD: "Marcus84@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./src
      dockerfile: TesteTecnicoMarcus.Api/Dockerfile
    container_name: teste-tecnico-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=TesteMarcusDB;User=sa;Password=Marcus84@;TrustServerCertificate=True"
    ports:
      - "5000:8080"
    depends_on:
      - db

  front:
    build:
      context: ./teste-tecnico-marcus-web
      dockerfile: Dockerfile
    container_name: teste-tecnico-front
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  sql_data:
